# -*- coding: utf-8 -*-
"""Despliegue-BDMoraMayor con streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWSooCv6s1Hs7dKNR67oRnf-S30oBn_o

#Despliegue
- Cargamos el modelo
- Cargamos los datos futuros
- Preparar los datos futuros
- Aplicamos el modelo para la predicción
"""

#Cargamos librerías principales
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import gdown
import pickle

# ID del archivo en Drive
file_id = "1MuslXQNIRERw6HGYF9Wytub5HRWK9ZO_"
url = f"https://drive.google.com/uc?id={file_id}"
output = "modelo-cla.pkl"

# Descargar desde Drive
gdown.download(url, output, quiet=False)

# Cargar el modelo
with open(output, "rb") as f:
    modelo_rf, labelencoder, variables, min_max_scaler = pickle.load(f)

# Se cargan los datos
#data = pd.read_csv("BD_MORA_MAYOR_FUTUROS.csv") #Cargar datos
#data.head() #muestras los 5 primeros registros

#Interfaz gráfica

#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

st.title('Predicción de entrada en Mora Mayor')

EDAD = st.slider('EDAD', min_value=18, max_value=84, value=30, step=1)
NUMERO_HIJOS = st.slider('NUMERO_HIJOS', min_value=0, max_value=20, value=0, step=1)
ESTRATO = st.selectbox('ESTRATO', ['1','2', '3','4','5','6'])
TIPO_VIVIENDA = st.selectbox('TIPO_VIVIENDA', ['FAMILIAR', 'PROPIA','ALQUILADA','ASIGNADA POR LA EMPRESA'])
IND_NAR = st.selectbox('IND_NAR', ['Antiguo', 'Nuevo', 'Recuperado', 'Nuevoe'])
NOTA = st.selectbox('NOTA', ['1', '2', '3', '4', '5' ])
NIVEL_INGRESOS_ACTUAL = st.slider('NIVEL_INGRESOS_ACTUAL', min_value=128571, max_value=50000000, value=128571 , step=10000)
IND_AGRO = st.selectbox('IND_AGRO', ['0', '1'])
MONTO_DESEMBOLSADO = st.slider('MONTO_DESEMBOLSADO', min_value=11646, max_value=641500000, value=11646 , step=10000)



#Dataframe
datos = [[EDAD, NUMERO_HIJOS,ESTRATO,TIPO_VIVIENDA,IND_NAR, NOTA, NIVEL_INGRESOS_ACTUAL, IND_AGRO, MONTO_DESEMBOLSADO]]
data = pd.DataFrame(datos, columns=['EDAD', 'NUMERO_HIJOS','ESTRATO','TIPO_VIVIENDA','IND_NAR','NOTA','NIVEL_INGRESOS_ACTUAL','IND_AGRO','MONTO_DESEMBOLSADO']) #Dataframe con los mismos nombres de variables

#Se realiza la preparación de datos
data_preparada = data.copy()

#En despliegue drop_first = False
data_preparada = pd.get_dummies(data_preparada, columns=['TIPO_VIVIENDA','IND_NAR','IND_AGRO'])
data_preparada.head()

#Se adicionan los columnas faltantes
data_preparada = data_preparada.reindex(columns=variables, fill_value=0)
data_preparada.head()

#Se normaliza la edad para predecir con Knn, Red, SNM, (arboles no se hace normalizacion)
#En los despliegues no se llama fit
#data_preparada[['Edad']]=min_max_scaler.transform(data_preparada[['Edad']])
#data_preparada.head()

"""#Predicciones"""

#Hacemos la predicción con el Tree
Y_pred = modelo_rf.predict(data_preparada)
print(Y_pred)

data['Prediccion'] = Y_pred
data.head()

#Precciones finales
data

#Recordar medida de error del modelo
st.warning("El modelo tiene un error del 11% , Porcentaje de error calculado Accuracy")